/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculatordemo2;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;
import javax.swing.*;

import java.lang.reflect.Field;  // This brings in the Field feature of Java Reflection

class CalculatorUITest {

    private static CalculatorUI classUnderTest;
    JTextArea textArea = new JTextArea();
    ButtonFactory button = new ButtonFactory();

    @BeforeAll
    public static void setUp() {
        classUnderTest = new CalculatorUI();
        
    }

    @DisplayName("Testing that writer writes the display")
    @Test
    public void writerSetText() throws Exception {
        // Use reflection to access the private field “text”
        Class cls = classUnderTest.getClass();
        Field field = cls.getDeclaredField("text");
        field.setAccessible(true);
        // Set the value of “text” to “mytext”
        JTextArea text = (JTextArea) field.get(classUnderTest);
        text.setText("mytext");
        // Test that the value of “text” is “mytext”
        assertEquals("mytext", text.getText());
    }

    @Test
    void test1num() {
        button.createNumericButton(5, textArea).doClick();
        assertEquals("5", textArea.getText());
    }
    @Test
    void test2num() {
        button.createNumericButton(3, textArea).doClick();
        button.createNumericButton(5, textArea).doClick();
        assertEquals("35", textArea.getText());
    }

    @Test
    void testCreatePrimitiveOperatorButtonAction() {
        Calculator calculator = new Calculator();
        button.createPrimitiveOperatorButton("+", textArea, calculator).doClick();
        assertEquals(" + ", textArea.getText());
    }
    
    
  
    @Test 
    void appPanelIsCreated() {
        assertNotNull(classUnderTest, "app should have a panel object");
    }
}

